version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env.production
    depends_on:
      - mongo
    networks:
      - blog-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - blog-network

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - blog-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_OPTIONS_EDITORTHEME: default
    networks:
      - blog-network
    

networks:
  blog-network:
    driver: bridge

volumes:
  mongo_data:
