version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env.production
    depends_on:
      - mongo
    networks:
      - blog-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - blog-network

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  mongo_data:
