version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env.production
    depends_on:
      - mongo
    networks:
      - mern-network


  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - mern-network


  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mern-network

    
  # nginx:
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - server
  #     - client
  #   networks:
  #     - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo_data:
